version: '3'

x-loki-logging: &lokilogging
  driver: json-file
  options:
    tag: "{{.Name}}"

services:

  raw_recorder:
    # image: ptgprocess:latest
    build:
      context: ./recorder
    container_name: raw_recorder
    restart: unless-stopped
    environment:
      PTG_URL: "$PTG_URL"
    volumes:
      - ${VOLUMES}/recordings/raw:/src/app/recordings
    command: -m ptgprocess.processors.record raw run --continuous

  video_recorder:
    # image: ptgprocess:latest
    build:
      context: ./recorder
    container_name: video_recorder
    restart: unless-stopped
    environment:
      PTG_URL: "$PTG_URL"
    volumes:
      - ${VOLUMES}/recordings/post:/src/app/recordings
      - ${VOLUMES}/recordings/raw:/src/app/raw
    command: -m ptgprocess.processors.record video run --continuous

  audio_recorder:
    # image: ptgprocess:latest
    build:
      context: ./recorder
    container_name: audio_recorder
    restart: unless-stopped
    environment:
      PTG_URL: "$PTG_URL"
    volumes:
      - ${VOLUMES}/recordings/post:/src/app/recordings
      - ${VOLUMES}/recordings/raw:/src/app/raw
    command: -m ptgprocess.processors.record audio run --continuous

  json_recorder:
    # image: ptgprocess:latest
    build:
      context: ./recorder
    container_name: json_recorder
    restart: unless-stopped
    environment:
      PTG_URL: "$PTG_URL"
    volumes:
      - ${VOLUMES}/recordings/post:/src/app/recordings
      - ${VOLUMES}/recordings/raw:/src/app/raw
    command: -m ptgprocess.processors.record json run --continuous

  # parquet_recorder:
  #   # image: ptgprocess:latest
  #   build:
  #     context: ./recorder
  #   container_name: parquet_recorder
  #   restart: unless-stopped
  #   environment:
  #     PTG_URL: "$PTG_URL"
  #   volumes:
  #     - ${VOLUMES}/recordings/post:/src/app/recordings
  #     - ${VOLUMES}/recordings/raw:/src/app/raw
  #   command: -m ptgprocess.processors.record parquet run --continuous

  pointcloud_recorder:
    # image: ptgprocess:latest
    build:
      context: ./recorder
    container_name: pointcloud_recorder
    restart: unless-stopped
    environment:
      PTG_URL: "$PTG_URL"
    volumes:
      - ${VOLUMES}/recordings/post:/src/app/recordings
      - ${VOLUMES}/recordings/raw:/src/app/raw
    command: -m ptgprocess.processors.record pointcloud run --continuous


# connect these containers to the server containers
networks:
  default:
    external: true
    name: ptg
