version: '3'

x-loki-logging: &lokilogging
  driver: json-file
  options:
    tag: "{{.Name}}"

services:

  # Machine Learning for Streams

  yolo3d:
    build: ./yolo
    container_name: yolo
    depends_on:
      - app
    restart: unless-stopped
    logging: *lokilogging

  clip_zero:
    build: ./clip-zero
    container_name: clip_zero
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - app
    restart: unless-stopped
    logging: *lokilogging


# connect these containers to the server containers
networks:
  default:
    external: true
    name: ptg-api-server_default
