version: '3'

services:

  # 

  # actionclip:
  #   image: ptgprocess
  #   container_name: actionclip
  #   volumes:
  #     - ${VOLUMES}/models:/src/lib/ptgprocess/models
  #     - ${VOLUMES}/models/pretrained-clip/:/root/.cache/clip
  #   restart: unless-stopped
  #   command: -m ptgprocess.processors.clip action2 run --continuous

  reasoning:
    build: ./reasoning
    container_name: reasoning
    restart: unless-stopped

  memory:
    build: ./memory
    container_name: memory
    restart: unless-stopped

