name: Push to GitLab

on:
  push:
    branches:
      - gitlab

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  # Shallow clone to speed up initial checkout

    - name: Convert to full repository
      run: git fetch --unshallow

    - name: Ensure main branch exists
      run: |
        git checkout -b main || git checkout main
        
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git config --global http.postBuffer 10000000  # 10 MB
        
    - name: Add GitLab remote and push
      env:
        GITLAB_URL: ${{ secrets.GITLAB_URL }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git remote set-url origin https://oauth2:$GITLAB_TOKEN@$GITLAB_URL
        git push origin main
